/**
 * @file main.c
 * @author Danny Dole-Muiños
 * @date 03/21/24
 * @note UART over USB serial
*/

// Preprocessor directives
// "#include" essentially pastes the included file here
// .c files (like the one we're in) are called "source files"
// .h files (like those included) are called "header files"
// Really only header files are ever included
#include "main.h"

// We have to DECLARE functions in C before they are used (this is called a function declaration)
// Because we have the declaration here, we can call SystemClock_Config() and MX_GPIO_Init() in main()
// The DEFINITION is also in this file (this is called a function definition) below main
// You can only call functions BELOW where they are declared
void SystemClock_Config(void);
void GPIO_Init(void);

/**
 * @brief  The application entry point.
 * @retval int
 */
int main(void)
{
    /* STM32F4xx HAL library initialization:
        - Configure the Flash prefetch, instruction and Data caches
        - Configure the Systick to generate an interrupt each 1 msec
        - Set NVIC Group Priority to 4
        - Global MSP (MCU Support Package) initialization
        */
    HAL_Init();

    // Autogenerated (by CubeMX) function that sets system clock speeds, turns on peripheral clock
    // Without this, we could not talk to any peripherals (cause clocks are needed to get data in or out of them)
    SystemClock_Config();

    // Turn on GPIO clocks
    // Without clocks on, we could not use any pins on the board, including those used for UART
    GPIO_Init();

    /*##-1- Configure the UART peripheral ######################################*/
    /* Put the USART peripheral in the Asynchronous mode (UART Mode) */
    /* UART1 configured as follows:
        - Word Length = 8 Bits
        - Stop Bit = One Stop bit
        - Parity = ODD parity
        - BaudRate = 9600 baud
        - Hardware flow control disabled (RTS and CTS signals) */

    /* UART handler declaration and definition */
    UART_HandleTypeDef uartHandle = {0};
    uartHandle.Instance          = USART2;
    uartHandle.Init.BaudRate     = 9600;
    uartHandle.Init.WordLength   = UART_WORDLENGTH_8B;  
    uartHandle.Init.StopBits     = UART_STOPBITS_1;
    uartHandle.Init.Parity       = UART_PARITY_NONE;    // STM32 Quirk: If you want to use a parity bit, the word length must be 9
    uartHandle.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    uartHandle.Init.Mode         = UART_MODE_TX_RX;
    uartHandle.Init.OverSampling = UART_OVERSAMPLING_16;
    if (HAL_UART_Init(&uartHandle) != HAL_OK)   // Note this calls HAL_UART_MspInit() in \Core\Src\stm32f4xx_hal_msp.c
    {                                           // which configures the correct GPIO to alternative mode.
        Error_Handler();                        // for them, the alt mode is USART2!
    }

    char buf[8] = "MIKU\n";

    while (1)   
    { 
        HAL_UART_Transmit(&uartHandle, buf, sizeof(buf), HAL_MAX_DELAY);
        HAL_Delay(1000);
    }
}

// ARRRRRG... BELOW HERE THERE BE AUTO-GENERATED CODE, YOU CAN IGNORE IT FOR NOW

/**
 * @brief System Clock Configuration
 * @retval None
 */
void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    /** Configure the main internal regulator output voltage
     */
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE3);

    /** Initializes the RCC Oscillators according to the specified parameters
     * in the RCC_OscInitTypeDef structure.
     */
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLM = 16;
    RCC_OscInitStruct.PLL.PLLN = 336;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV4;
    RCC_OscInitStruct.PLL.PLLQ = 2;
    RCC_OscInitStruct.PLL.PLLR = 2;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
    {
        Error_Handler();
    }

    /** Initializes the CPU, AHB and APB buses clocks
     */
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
    {
        Error_Handler();
    }
}

/**
 * @brief GPIO Initialization Function
 * @param None
 * @retval None
 */
void GPIO_Init(void)
{
    /* GPIO Ports Clock Enable */
    __HAL_RCC_GPIOC_CLK_ENABLE();
    __HAL_RCC_GPIOH_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
}

/**
 * @brief  This function is executed in case of error occurrence.
 * @retval None
 */
void Error_Handler(void)
{
    /* USER CODE BEGIN Error_Handler_Debug */
    /* User can add his own implementation to report the HAL error return state */
    __disable_irq();
    while (1)
    {
    }
    /* USER CODE END Error_Handler_Debug */
}

#ifdef USE_FULL_ASSERT
/**
 * @brief  Reports the name of the source file and the source line number
 *         where the assert_param error has occurred.
 * @param  file: pointer to the source file name
 * @param  line: assert_param error line source number
 * @retval None
 */
void assert_failed(uint8_t *file, uint32_t line)
{
    /* USER CODE BEGIN 6 */
    /* User can add his own implementation to report the file name and line number,
       ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
    /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
