/**
 * @file main.c
 * @author Danny Dole-Muiños
 * @date 03/21/24
 * @note Lab 0 solution with lotsa comments
*/

// Preprocessor directives
// "#include" essentially pastes the included file here
// .c files (like the one we're in) are called "source files"
// .h files (like those included) are called "header files"
// Really only header files are ever included
#include "main.h"
#include "stm32f446xx.h"

// We have to DECLARE functions in C before they are used (this is called a function declaration)
// Because we have the declaration here, we can call SystemClock_Config() and MX_GPIO_Init() in main()
// The DEFINITION is also in this file (this is called a function definition) below main
// You can only call functions BELOW where they are declared
void SystemClock_Config(void);
void MX_GPIO_Init(void);

/**
 * @brief  The application entry point.
 * @retval int
 */
int main(void)
{
    // We do our initializations in this section, before we enter our endless loop (the while(1) at the bottom of main)

    // Autogenerated (by CubeMX) function that sets system clock speeds, turns on peripheral clock
    // Without this, we could not talk to any peripherals (cause clocks are needed to get data in or out of them)
    SystemClock_Config();

    // Autogenerated (by CubeMX) function that turns on GPIO peripheral clocks for Ports A, B, C, and H
    // B and H are maybe vestigial/unneeded, CubeMX had some reason to turn on those clocks tho
    // If we don't turn on the clocks, you can't talk to the GPIO Port
    MX_GPIO_Init();

    // GPIOC Pin 13 Setup //
    // PC13 is wired up externally to the user button (B1) on the Nucleo board
    // It's already configured!!!! cause the default config for a pin is:
    // - Mode (register MODER): Input
    // - Pull-Up/Pull-Down (register PUPDR): No Pull-Up/Pull-Down
    // ...which are both defined as 0b0/0b00, AND the default for those registers per the reference manual is all 0s,
    // so it's already set as input and no pull up/-down by default

    // GPIOA Pin 5 Setup //
    // PA5 is wired up externally to the user LED (LD2) on the Nucleo board
    GPIOA->ODR = 0x00000000; // Clear output data register as precaution
    GPIOA->MODER |= 0x400;   // Set MODER5[1:0] to 0b01 (General purpose output mode)
    // Don't need to worry about pull-up/-down, output devices don't care so that setting would be ignored!

    while (1)   // 1 is true, so while(1) is an endless loop
    { 
        // CMSIS SOLUTION
        // If button pressed
        if (GPIOC->IDR & GPIO_PIN_13)   // Bitwise AND (&)
        {   
            // Turn LED on (ACTIVE_LOW)
            // By "active low," I mean that "the device (LED) is active (LED turned on) when the logic level is low"
            // Logic level high is 1, logic level low is 0
            // Logic level high is 3.3V, logic level low is 0V
            // So to actually turn the LED on, we have to clear the bit!
            GPIOA->ODR &= ~(GPIO_PIN_5); // Set PA5 ("set" means set to 1); ~ is complement/bitwise NOT operator
        }
        else
        {
            // Turn LED off
            GPIOA->ODR |= (GPIO_PIN_5); // Clear PA5 ("clear" means set to 0); Bitwise OR (|)
        }
        // More about if statements: https://www.w3schools.com/c/c_conditions.php
        // More about else statements: https://www.w3schools.com/c/c_conditions_else.php
        // More about while: https://www.w3schools.com/c/c_while_loop.php 
        // More about C operators: https://www.w3schools.com/c/c_operators.php
    }
}

// ARRRRRG... BELOW HERE THERE BE AUTO-GENERATED CODE, YOU CAN IGNORE IT FOR NOW

/**
 * @brief System Clock Configuration
 * @retval None
 */
void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    /** Configure the main internal regulator output voltage
     */
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE3);

    /** Initializes the RCC Oscillators according to the specified parameters
     * in the RCC_OscInitTypeDef structure.
     */
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLM = 16;
    RCC_OscInitStruct.PLL.PLLN = 336;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV4;
    RCC_OscInitStruct.PLL.PLLQ = 2;
    RCC_OscInitStruct.PLL.PLLR = 2;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
    {
        Error_Handler();
    }

    /** Initializes the CPU, AHB and APB buses clocks
     */
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
    {
        Error_Handler();
    }
}

/**
 * @brief GPIO Initialization Function
 * @param None
 * @retval None
 */
void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};
    /* USER CODE BEGIN MX_GPIO_Init_1 */
    /* USER CODE END MX_GPIO_Init_1 */

    /* GPIO Ports Clock Enable */
    __HAL_RCC_GPIOC_CLK_ENABLE();
    __HAL_RCC_GPIOH_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
}

/**
 * @brief  This function is executed in case of error occurrence.
 * @retval None
 */
void Error_Handler(void)
{
    /* USER CODE BEGIN Error_Handler_Debug */
    /* User can add his own implementation to report the HAL error return state */
    __disable_irq();
    while (1)
    {
    }
    /* USER CODE END Error_Handler_Debug */
}

#ifdef USE_FULL_ASSERT
/**
 * @brief  Reports the name of the source file and the source line number
 *         where the assert_param error has occurred.
 * @param  file: pointer to the source file name
 * @param  line: assert_param error line source number
 * @retval None
 */
void assert_failed(uint8_t *file, uint32_t line)
{
    /* USER CODE BEGIN 6 */
    /* User can add his own implementation to report the file name and line number,
       ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
    /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
